# Fenêtre
LARGEUR_FENETRE = 200
HAUTEUR_FENETRE = 150
TITRE_FENETRE = "Pong"
FPS=60
# Raquettes
RAQUETTE_VITESSE = 4
RAQUETTE_HAUTEUR = 15
RAQUETTE_LARGEUR = 3
RAQUETTE_Y_MIN = 10
RAQUETTE_Y_MAX = 110
RAQUETTE_VITESSE = 2
RAQUETTE_ESPACE_X = 8
RAQUETTE_Y_INIT = HAUTEUR_FENETRE/2 - RAQUETTE_HAUTEUR/2
# Balle
BAL_TAILLE = 1
BAL_COULEUR = 7
BAL_RAYON = 3
BAL_RAYON = 3
# Menu

MENU_COULEUR = 7
MENU_X_PRINCIPAL = 20
MENU_Y_PRINCIPAL = 50
MENU_X_PARAM = 120
MENU_Y_PARAM = 110

# Code de triche
CODE_TRICHE_CONTEUR_MAX = 3
CODE_TRICHE_TIMER_MAX = 1.5
